import type { Language, Translation } from "@/lib/translation-types"

const languageData = [
  ["AF", "Afrikaans", "af"],
  ["SQ", "Albanian", "sq"],
  ["AM", "Amharic", "am"],
  ["AR", "Arabic", "ar"],
  ["HY", "Armenian", "hy"],
  ["AS", "Assamese", "as"],
  ["AY", "Aymara", "ay"],
  ["AZ", "Azerbaijani", "az"],
  ["BM", "Bambara", "bm"],
  ["EU", "Basque", "eu"],
  ["BE", "Belarusian", "be"],
  ["BN", "Bengali", "bn"],
  ["BHO", "Bhojpuri", "bho"],
  ["BS", "Bosnian", "bs"],
  ["BG", "Bulgarian", "bg"],
  ["CA", "Catalan", "ca"],
  ["CEB", "Cebuano", "ceb"],
  ["ZH", "Chinese (Simplified)", "zh-CN"],
  ["ZH", "Chinese (Traditional)", "zh-TW"],
  ["CO", "Corsican", "co"],
  ["HR", "Croatian", "hr"],
  ["CS", "Czech", "cs"],
  ["DA", "Danish", "da"],
  ["DV", "Dhivehi", "dv"],
  ["DOI", "Dogri", "doi"],
  ["NL", "Dutch", "nl"],
  ["EO", "Esperanto", "eo"],
  ["ET", "Estonian", "et"],
  ["EE", "Ewe", "ee"],
  ["FIL", "Filipino", "tl"],
  ["FI", "Finnish", "fi"],
  ["FR", "French", "fr"],
  ["FY", "Frisian", "fy"],
  ["GL", "Galician", "gl"],
  ["KA", "Georgian", "ka"],
  ["DE", "German", "de"],
  ["EL", "Greek", "el"],
  ["GN", "Guarani", "gn"],
  ["GU", "Gujarati", "gu"],
  ["HT", "Haitian Creole", "ht"],
  ["HA", "Hausa", "ha"],
  ["HAW", "Hawaiian", "haw"],
  ["HE", "Hebrew", "iw"],
  ["HI", "Hindi", "hi"],
  ["HMN", "Hmong", "hmn"],
  ["HU", "Hungarian", "hu"],
  ["IS", "Icelandic", "is"],
  ["IG", "Igbo", "ig"],
  ["ILO", "Ilocano", "ilo"],
  ["ID", "Indonesian", "id"],
  ["GA", "Irish", "ga"],
  ["IT", "Italian", "it"],
  ["JA", "Japanese", "ja"],
  ["JV", "Javanese", "jw"],
  ["KN", "Kannada", "kn"],
  ["KK", "Kazakh", "kk"],
  ["KM", "Khmer", "km"],
  ["RW", "Kinyarwanda", "rw"],
  ["KOK", "Konkani", "gom"],
  ["KO", "Korean", "ko"],
  ["KR", "Krio", "kri"],
  ["KU", "Kurdish (Kurmanji)", "ku"],
  ["CKB", "Kurdish (Sorani)", "ckb"],
  ["KY", "Kyrgyz", "ky"],
  ["LO", "Lao", "lo"],
  ["LA", "Latin", "la"],
  ["LV", "Latvian", "lv"],
  ["LN", "Lingala", "ln"],
  ["LT", "Lithuanian", "lt"],
  ["LG", "Luganda", "lg"],
  ["LB", "Luxembourgish", "lb"],
  ["MK", "Macedonian", "mk"],
  ["MAI", "Maithili", "mai"],
  ["MG", "Malagasy", "mg"],
  ["MS", "Malay", "ms"],
  ["ML", "Malayalam", "ml"],
  ["MT", "Maltese", "mt"],
  ["MI", "Maori", "mi"],
  ["MR", "Marathi", "mr"],
  ["MN", "Mongolian", "mn"],
  ["MY", "Myanmar (Burmese)", "my"],
  ["NE", "Nepali", "ne"],
  ["NO", "Norwegian", "no"],
  ["NY", "Nyanja", "ny"],
  ["OR", "Odia", "or"],
  ["OM", "Oromo", "om"],
  ["PS", "Pashto", "ps"],
  ["FA", "Persian", "fa"],
  ["PL", "Polish", "pl"],
  ["PT", "Portuguese", "pt"],
  ["PA", "Punjabi", "pa"],
  ["QU", "Quechua", "qu"],
  ["RO", "Romanian", "ro"],
  ["RU", "Russian", "ru"],
  ["SM", "Samoan", "sm"],
  ["SA", "Sanskrit", "sa"],
  ["GD", "Scots Gaelic", "gd"],
  ["NSO", "Sepedi", "nso"],
  ["SR", "Serbian", "sr"],
  ["ST", "Sesotho", "st"],
  ["SN", "Shona", "sn"],
  ["SD", "Sindhi", "sd"],
  ["SI", "Sinhala", "si"],
  ["SK", "Slovak", "sk"],
  ["SL", "Slovenian", "sl"],
  ["SO", "Somali", "so"],
  ["ES", "Spanish", "es"],
  ["SU", "Sundanese", "su"],
  ["SW", "Swahili", "sw"],
  ["SV", "Swedish", "sv"],
  ["TG", "Tajik", "tg"],
  ["TA", "Tamil", "ta"],
  ["TT", "Tatar", "tt"],
  ["TE", "Telugu", "te"],
  ["TH", "Thai", "th"],
  ["TI", "Tigrinya", "ti"],
  ["TS", "Tsonga", "ts"],
  ["TR", "Turkish", "tr"],
  ["TK", "Turkmen", "tk"],
  ["AK", "Twi", "ak"],
  ["UK", "Ukrainian", "uk"],
  ["UR", "Urdu", "ur"],
  ["UG", "Uyghur", "ug"],
  ["UZ", "Uzbek", "uz"],
  ["VI", "Vietnamese", "vi"],
  ["CY", "Welsh", "cy"],
  ["XH", "Xhosa", "xh"],
  ["YI", "Yiddish", "yi"],
  ["YO", "Yoruba", "yo"],
  ["ZU", "Zulu", "zu"],
] as const
const languageRegions: Record<string, string> = {
  af: "ZA",
  am: "ET",
  ar: "SA",
  as: "IN",
  bn: "BD",
  bho: "IN",
  ceb: "PH",
  ckb: "IQ",
  dv: "MV",
  fil: "PH",
  fy: "NL",
  gu: "IN",
  ha: "NG",
  haw: "US",
  he: "IL",
  hi: "IN",
  hmn: "CN",
  ig: "NG",
  ilo: "PH",
  iw: "IL",
  jv: "ID",
  kn: "IN",
  kok: "IN",
  kr: "LR",
  ku: "TR",
  la: "VA",
  lg: "UG",
  ln: "CD",
  mai: "IN",
  ml: "IN",
  mn: "MN",
  my: "MM",
  ne: "NP",
  nso: "ZA",
  ny: "MW",
  om: "ET",
  or: "IN",
  pa: "IN",
  ps: "AF",
  qu: "PE",
  rw: "RW",
  sa: "IN",
  sd: "PK",
  si: "LK",
  sn: "ZW",
  so: "SO",
  st: "LS",
  su: "ID",
  sw: "KE",
  ta: "IN",
  te: "IN",
  ti: "ER",
  tl: "PH",
  ts: "ZA",
  ur: "PK",
  ug: "CN",
  uz: "UZ",
  xh: "ZA",
  yi: "IL",
  yo: "NG",
  zu: "ZA",
}
export function flagForLocale(locale: string) {
  const region =
    languageRegions[locale] ?? new Intl.Locale(locale).maximize().region
  return /^[a-z]{2}$/i.test(region ?? "") ? region.toLowerCase() : "un"
}
export const languages: Language[] = languageData.map(
  ([code, name, locale]) => ({
    code,
    name,
    locale,
  })
)
export const autoLanguage: Language = {
  code: "AUTO",
  name: "Auto detect",
  locale: "auto",
}
const demos: Record<string, string> = {
  es: "Hola, ¿cómo estás?",
  fr: "Bonjour, comment allez-vous ?",
  de: "Hallo, wie geht es dir?",
  ja: "こんにちは、お元気ですか？",
  ko: "안녕하세요, 잘 지내세요?",
  ar: "مرحبًا، كيف حالك؟",
  it: "Ciao, come stai?",
  pt: "Olá, como você está?",
  "zh-CN": "你好，你好吗？",
  hi: "नमस्ते, आप कैसे हैं?",
}
export function fallback(phrase: string, language: Language): Translation {
  return {
    ...language,
    text:
      phrase.trim().toLowerCase() === "hello, how are you?"
        ? (demos[language.locale] ?? phrase)
        : `${phrase} · ${language.name}`,
  }
}
